# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 00745a96b03263f149a08477b0d8a6e990adde8a9b8cd0751227a7e61b207f00aaffb0fb4d18627d0b2e758c28a4fe7c6d61ad965be051d6204876887ce88dbc

test:
  secret_key_base: 327bd573911457fc6edd51c532627f8953ee276bb25e7fd7830719987f99fe69fdced4672058e76abd201c6d1fef323ac07c23b89fb45d682eaf9c551414a5cd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
